[project]
name = "velocity-ft"
requirements = []
[contracts.ft-trait]
path = "contracts/ft-trait.clar"
depends_on = []

[contracts.vbucks-game]
path = "contracts/vbucks-game.clar"
depends_on = ['velocity-ft']

[contracts.velocity-ft]
path = "contracts/velocity-ft.clar"
depends_on = []
