[project]
name = "clarity-ft"
requirements = []
[contracts.app]
path = "contracts/app.clar"
depends_on = ["my-ft"]

[contracts.ft-trait]
path = "contracts/ft-trait.clar"
depends_on = []

[contracts.my-ft]
path = "contracts/my-ft.clar"
depends_on = ["ft-trait"]
